const images = {
	cart : require('./cart.png'),
	product1 : require('./product1.webp'),
	product1h : require('./product1-hover.webp'),
	product2 : require('./product2.webp'),
	product2h : require('./product2-hover.webp'),
	product3 : require('./product3.webp'),
	product3h : require('./product3-hover.webp'),
	product4 : require('./product4.webp'),
	product4h : require('./product4-hover.webp'),
	product5 : require('./product5.webp'),
	product5h : require('./product5-hover.webp'),
	product6 : require('./product6.webp'),
	product6h : require('./product6-hover.webp'),
	product7 : require('./product7.webp'),
	product7h : require('./product7-hover.webp'),
	product8 : require('./product8.webp'),
	product8h : require('./product8-hover.webp'),
	product9 : require('./product9.webp'),
	product9h : require('./product9-hover.webp'),
	product10 : require('./product10.webp'),
	product10h : require('./product10-hover.webp'),
	product11 : require('./product11.webp'),
	product11h : require('./product11-hover.webp'),
	product12 : require('./product12.webp'),
	product12h : require('./product12-hover.webp'),
	product13 : require('./product13.webp'),
	product13h : require('./product13-hover.webp'),
	product14 : require('./product14.webp'),
	product14h : require('./product14-hover.webp'),
	product15 : require('./product15.webp'),
	product15h : require('./product15-hover.webp'),
	product16 : require('./product16.webp'),
	product16h : require('./product16-hover.webp'),
}
export default images

